# Generated by Django 6.0.2 on 2026-03-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Card', 'Card'), ('UPI', 'UPI'), ('NetBanking', 'Net Banking'), ('COD', 'Cash on Delivery')], max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
